### ISSUE TITLE
 Could not find 'bsdtar' on $PATH.

### ISSUE THREAD

**Issue by aisuneko** [AppImageCrafters/build-appimage-action#6]
I have this workflow right here, basically taken from the [example](https://appimage-builder.readthedocs.io/en/latest/hosted-services/github-actions.html) in the docs:
```
name: C/C++ AppImage

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-default qtdeclarative5-dev cmake libarchive-tools 
      - name: configure
        run: qmake
      - name: build
        run: make
      - name: create directory
        run: mkdir -p AppDir/usr/bin
      - name: copy binary
        run: mv selectdefaultapplication AppDir/usr/bin/
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        env:
          UPDATE_INFO: gh-releases-zsync|magnus-ISU|selectdefaultapplication|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
```
I got this error output at the "Build AppImage" step:
```
Run AppImageCrafters/build-appimage@master
/usr/bin/docker run --name appimagecraftersappimagebuilder110_c0fb5c --label 8d5581 --workdir /github/workspace --rm -e "UPDATE_INFO" -e "INPUT_RECIPE" -e "INPUT_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/selectdefaultapplication/selectdefaultapplication":"/github/workspace" appimagecrafters/appimage-builder:1.1.0  "appimage-builder" "--recipe=AppImageBuilder.yml" "--skip-test"
INFO:main:Running main script
INFO:main:Running pacman deploy
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/__main__.py", line 50, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/commands/pacman_deploy.py", line 42, in __call__
    venv = Venv(
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/deploy/pacman/venv.py", line 57, in __init__
    self._deps = shell.require_executables(DEPENDS_ON)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/utils/shell.py", line 16, in require_executables
    paths[dep] = require_executable(dep)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/utils/shell.py", line 23, in require_executable
    raise CommandNotFoundError("Could not find '{exe}' on $PATH.".format(exe=tool))
appimagebuilder.utils.shell.CommandNotFoundError: Could not find 'bsdtar' on $PATH.
```
I believe that `bsdtar` should be part of `libarchive-tools` on Ubuntu 20.04(latest version used by GitHub Actions); if so, why is that?

**Comment by dragos240** [comment]
I'm getting this problem too

**Comment by pzhlkj6612** [comment]
@aisuneko:

> I believe that `bsdtar` should be part of `libarchive-tools` on Ubuntu 20.04(latest version used by GitHub Actions); if so, why is that?

Well, `libarchive-tools` was not installed. The image has been flawed:

```console
$ docker run -it --rm appimagecrafters/appimage-builder:1.1.0 bash -c \
> 'grep 'PRETTY_NAME' /etc/os-release; command -v bsdtar; echo $?; apt list libarchive-tools'
PRETTY_NAME="Ubuntu 20.04.4 LTS"
1
Listing... Done
libarchive-tools/focal-updates,focal-security 3.4.0-2ubuntu1.2 amd64
N: There is 1 additional version. Please use the '-a' switch to see it

```

And,

> ```
>       ...
>       - name: Build AppImage
>         uses: AppImageCrafters/build-appimage@v1
>         ...
> ```
> 
> 
> ```
> Run AppImageCrafters/build-appimage@master
> ...
> ```

The versions of that action in your post are not the same, by the way.

**Comment by pzhlkj6612** [comment]
To all subscribers:

This project lacks maintenance and management, so personally I would recommend you have a look at another AppImage project: https://github.com/AppImage
